import streamlit as st
import tempfile
from datetime import date
from backend.calculations import get_total_savings, get_total_loan_given, get_wallet_balance
from backend.db import get_db_connection
from pdf.generator import generate_shg_report

# 1. PAGE CONFIG & AUTH SHIELD
st.set_page_config(layout="wide", page_title="SHG Reports")

if "logged_in" not in st.session_state or st.session_state.role != "president":
    st.switch_page("app.py")
    st.stop()

shg_id = st.session_state.shg_id
shg_no = st.session_state.get("shg_no", "N/A")

# 2. BILINGUAL DICTIONARY
if "lang" not in st.session_state:
    st.session_state.lang = "मराठी"

LANG = {
    "मराठी": {
        "title": "अहवाल व संदेश केंद्र", "period": "📅 अहवाल कालावधी निवडा",
        "from": "पासून", "to": "पर्यंत", "pdf_sec": "📥 PDF अहवाल जनरेट करा",
        "pdf_btn": "अहवाल तयार करा", "wa_sec": "📲 WhatsApp संदेश (कॉपी करा)",
        "info": "खालील संदेश निवडा आणि तुमच्या बचत गट ग्रुपवर पाठवा.",
        "back": "⬅️ डॅशबोर्ड", "wa_head": "महिला बचत गट अहवाल", "wa_total_sav": "एकूण बचत",
        "wa_total_loan": "एकूण कर्ज दिले", "wa_wallet": "उपलब्ध रक्कम", "wa_sign": "– अध्यक्ष", "group":"गट", "t_period":" कालावधी", "msg":"हा अहवाल सिस्टमद्वारे तयार केला आहे.", "note":"नोंद"
    },
    "English": {
        "title": "Reports & Messaging", "period": "📅 Select Report Period",
        "from": "From", "to": "To", "pdf_sec": "📥 Generate PDF Report",
        "pdf_btn": "Generate PDF", "wa_sec": "📲 WhatsApp Templates",
        "info": "Copy the message below and paste it into your SHG WhatsApp group.",
        "back": "⬅️ Dashboard", "wa_head": "SHG Progress Report", "wa_total_sav": "Total Savings",
        "wa_total_loan": "Total Loan Disbursed", "wa_wallet": "Available Funds", "wa_sign": "– President", "group":"Group", "t_period":"Period", "note":"Note", "msg":"This Message is Generated By The System."
    }
}
t = LANG[st.session_state.lang]

# 3. UI CUSTOM STYLING
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;500&display=swap');
    html, body, [class*="css"] { font-family: 'Inter', sans-serif !important; }
    
    .report-card {
        background: rgba(255, 255, 255, 0.03);
        border: 1px solid rgba(255, 255, 255, 0.1);
        padding: 25px; border-radius: 15px; height: 100%;
    }
    .wa-box {
        background-color: #075e54; color: white; padding: 15px;
        border-radius: 10px; font-family: monospace; font-size: 0.9rem;
    }
    </style>
    """, unsafe_allow_html=True)

# 4. DATA FETCHING
def get_shg_info(shg_id):
    conn = get_db_connection()
    cur = conn.cursor()
    cur.execute("SELECT shg_name, village FROM shg_groups WHERE id=%s", (shg_id,))
    row = cur.fetchone()
    cur.close(); conn.close()
    return row

shg_name, village = get_shg_info(shg_id)

# --- SAFETY SHIELD: MATH VALIDATION ---
raw_total_savings = get_total_savings(shg_id)
raw_total_loan = get_total_loan_given(shg_id)
raw_wallet = get_wallet_balance(shg_id)

# PDF safe values (Pie charts cannot take negative numbers)
pdf_safe_savings = max(0, raw_total_savings)
pdf_safe_loan = max(0, raw_total_loan)
pdf_safe_wallet = max(0, raw_wallet)

# 5. HEADER
col_h1, col_h2 = st.columns([3, 1])
with col_h1:
    st.markdown(f"<h1 style='font-weight:100; margin:0;'>{t['title']}</h1>", unsafe_allow_html=True)
    st.caption(f"SHG: {shg_name} | Village: {village}")
with col_h2:
    st.session_state.lang = st.selectbox("🌐", ["मराठी", "English"], 
                                         index=0 if st.session_state.lang == "मराठी" else 1, 
                                         label_visibility="collapsed")

st.divider()

# 6. MAIN CONTENT - TWO COLUMN LAYOUT
c1, c2 = st.columns([1, 1], gap="large")

with c1:
    st.markdown(f"### {t['period']}")
    d_col1, d_col2 = st.columns(2)
    with d_col1:
        from_date = st.date_input(t["from"], value=date.today().replace(day=1))
    with d_col2:
        to_date = st.date_input(t["to"], value=date.today())
    
    period_text = f"{from_date.strftime('%d %b %Y')} - {to_date.strftime('%d %b %Y')}"
    
    st.write("")
    st.markdown(f"### {t['pdf_sec']}")
    if st.button(t["pdf_btn"], use_container_width=True, type="primary"):
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
            pdf_path = tmp.name
        
        # We pass the validated safe values to the generator to avoid Matplotlib errors
        generate_shg_report(
            shg_id=shg_id,
            shg_name=f"{shg_name} ({village})",
            period_text=period_text,
            output_path=pdf_path
        )
        
        with open(pdf_path, "rb") as f:
            st.download_button(
                label="📥 Download PDF Now",
                data=f,
                file_name=f"Report_{shg_no}_{from_date}.pdf",
                mime="application/pdf",
                use_container_width=True
            )

with c2:
    st.markdown(f"### {t['wa_sec']}")
    st.info(t["info"])
    
    # Message Logic (Uses raw values to show the user exactly what is in the DB)
    wa_msg = f"""
✨ {t['wa_head']} ✨
━━━━━━━━━━━━━━━━━━━
📍 {t['group']} : {shg_name}
📅 {t['t_period']} : {period_text}
━━━━━━━━━━━━━━━━━━━
💰 {t['wa_total_sav']}: ₹{raw_total_savings:,}
💸 {t['wa_total_loan']}: ₹{raw_total_loan:,}
🏦 {t['wa_wallet']}: ₹{raw_wallet:,}
━━━━━━━━━━━━━━━━━━━
📢 {t['note']} : {t['msg']}
{t['wa_sign']}
    """.strip()

    st.text_area("Copy Message Below:", wa_msg, height=280)
    st.caption("Tip: Select all (Ctrl+A), Copy (Ctrl+C), and Paste in WhatsApp.")

# 7. NAVIGATION FOOTER
st.write("")
st.divider()
f_col1, f_col2 = st.columns(2)
with f_col1:
    if st.button(t["back"], use_container_width=True):
        st.switch_page("pages/dashboard.py")
with f_col2:
    if st.button("🔓 Logout", use_container_width=True):
        st.session_state.clear()
        st.switch_page("app.py")